# Generated by Django 5.1.5 on 2025-01-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_rename_genres_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
    ]
