# Generated by Django 5.1.5 on 2025-01-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Ator', 'verbose_name_plural': 'Atores'},
        ),
    ]
