# Generated by Django 5.1.5 on 2025-01-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='relase_date',
            new_name='release_date',
        ),
    ]
